# Generated by Django 4.0.4 on 2022-05-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_entrega_app', '0002_relative_age_relative_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relative',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
