# Generated by Django 4.0.4 on 2022-05-29 15:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tp_entrega_app', '0004_alter_relative_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relative',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 29, 15, 59, 23, 797835, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='relative',
            name='id',
            field=models.CharField(default=uuid.UUID('4f1476a4-df68-11ec-83ec-21f2948ad9d8'), max_length=10, primary_key=True, serialize=False),
        ),
    ]
