# Generated by Django 4.0.4 on 2022-05-30 02:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tp_entrega_app', '0005_alter_relative_birth_date_alter_relative_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relative',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 30, 2, 34, 11, 743879, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='relative',
            name='id',
            field=models.CharField(default='fd43d15e-d', max_length=10, primary_key=True, serialize=False),
        ),
    ]
